### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by jeekajoo** [y-lohse/cozy-archives#24]
Hi,
I can't seem to install cozy-frost :

> NPM Install failed: Error: NPM Install failed at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cozy-controller/build/server/lib/npm.js:59:17) at ChildProcess.emit (events.js:98:17) at maybeClose (child_process.js:755:16) at Socket.<anonymous> (child_process.js:968:11) at Socket.emit (events.js:95:17) at Pipe.close (net.js:465:12)

Data System: 2.5.5
Proxy: 2.5.6
Home: 2.5.9
Controller: 2.5.4

Thanks
J.

**Comment by jeekajoo** [comment]
works with node4
